# Generated by Django 2.1.7 on 2019-04-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('username', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
