# Generated by Django 2.1.7 on 2019-04-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('item', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
