# Generated by Django 2.1.7 on 2019-04-12 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phonenumber',
        ),
    ]
