# Generated by Django 2.1.7 on 2019-04-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20190421_1906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
