# Generated by Django 2.1.7 on 2019-04-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_account_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AddField(
            model_name='account',
            name='phonenumber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
