# Generated by Django 2.1.7 on 2019-04-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20190422_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cr_number',
            field=models.IntegerField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
