# Generated by Django 2.1.7 on 2019-05-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='address',
            field=models.DateField(null=True),
        ),
    ]
