# Generated by Django 2.1.7 on 2019-05-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_auto_20190501_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='address',
            field=models.CharField(max_length=120),
        ),
    ]
